suover/fit-on

src/main/reactfront/src/components/layout/sideNavBar/NavbarItem.ts, src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx, src/main/reactfront/src/components/layout/sideNavBar/StyledAvatar.tsx
페이지 좌측에 사용 할 사이드 메뉴 구현
- SideNavbar 구현
- 메뉴 아이템 설정 가능
- 확장 축소 기능
- 사이드바 넓이 선택 가능
- 사이드바 marginTop 설정 가능
- 메뉴 폰트 사이즈 선택 가능
- 메뉴 아이콘 사이즈 선택 가능
- 사이드바 하단 프로필 표시(사용 여부 선택 가능)
- badge (사용 여부 선택 가능)
- position 선택 가능
마이페이지 적용 예시
어떤 변경 사항이 있나요?
close #17
=> ✨ Feat: SideNavbar 구현 #17

src/main/reactfront/src/components/cardList/CardList.tsx, src/main/reactfront/src/components/contentCard/ContentCard.styles.ts, src/main/reactfront/src/components/contentCard/ContentCard.tsx, src/main/reactfront/src/components/productItem/ProductItem.styles.ts, src/main/reactfront/src/components/productItem/ProductItem.tsx
카드형 게시글과 게시판, 개별 상품 UI 구현
- 운동 정보와 루틴에서 공유할 컴포넌트 제작
- 상품 리스트에서 보여질 개별 상품 UI 제작
어떤 변경 사항이 있나요?
close #19
=> ✨ Feat: 카드형 게시글, 게시판, 개별 상품 UI 제작

src/main/reactfront/src/components/genericTable/GenericTable.tsx
GenericTable TableHead 코드 수정
- TableHead 체크박스 미사용시 첫번째 칸이 빈칸으로 표시되는 부분 수정
- 체크박스 사용시 체크박스 칸 width 설정 가능
- 체크박스 대신 다른 내용을 넣을 수 있도록 수정
어떤 변경 사항이 있나요?
close #25
=> ♻️ Refactor: GenericTable TableHead 코드 수정 #25

src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx
SideNavbar SideNavbarProps 코드 수정
SideNavbar SideNavbarProps 에서 margin, width, size 등의 단위를 더 다양하게 사용하기 위해 number 를 string 으로 변경
어떤 변경 사항이 있나요?
close #27
=> ♻️ Refactor: SideNavbar SideNavbarProps 코드 수정 #27

src/main/reactfront/src/components/cardList/CardList.tsx, src/main/reactfront/src/components/contentCard/ContentCard.tsx
공통으로 사용하는 카드 컴포넌트, 카드 리스트 코드 수정
- 루틴 데이터의 타입에 맞도록 카드 컴포넌트 데이터 타입 수정
- 파일명과 컴포넌트 이름 통일
어떤 변경 사항이 있나요?
close #29
=> ♻️ Refactor: 카드 컴포넌트, 카드 리스트 코드 수정

src/main/reactfront/src/components/common/genericButton/GenericButton.styles.ts, src/main/reactfront/src/components/common/genericButton/GenericButton.tsx
✨ Feat: 버튼 Component #40
버튼 Component UI 및 CSS 제작 
버튼 Component UI 및 CSS 제작
어떤 변경 사항이 있나요?
close #40
=> ✨ Feat: 버튼 Component #40

src/main/reactfront/src/components/common/SelectBox.tsx, src/main/reactfront/src/components/common/button/ButtonLikePost.tsx, src/main/reactfront/src/components/common/button/ButtonNewRoutine.tsx, src/main/reactfront/src/components/common/button/ButtonShare.tsx, src/main/reactfront/src/components/common/comment/CommentComponent.tsx, src/main/reactfront/src/components/common/comment/CommentLeave.tsx, src/main/reactfront/src/components/common/comment/CommentList.tsx, src/main/reactfront/src/components/common/comment/CommentsTemplate.tsx, src/main/reactfront/src/components/contentCard/ContentCard.tsx, src/main/reactfront/src/components/routine/RoutineBestList.tsx, src/main/reactfront/src/components/routine/RoutineCard.tsx, src/main/reactfront/src/components/routine/RoutineTotalList.tsx, src/main/reactfront/src/components/routine/ViewRoutine.tsx, src/main/reactfront/src/pages/routine/NewRoutine.tsx, src/main/reactfront/src/pages/routine/RoutineMain.tsx, src/main/reactfront/src/pages/routine/ViewRoutineDetail.tsx, src/main/reactfront/src/types/DummyData.tsx
운동 루틴 정보 메인페이지
운동 루틴 정보 화면 구현
운동 루틴 정보 작성 화면 구현
운동 루틴 페이지에 사용될 더미 데이터 및 버튼 추가
운동 루틴 정보 메인페이지
후에 스와이퍼 컴포넌트 제작 완료시, 코드 수정 필요
운동 루틴 정보 화면 구현
운동 루틴 정보 작성 화면 구현
Content Card props 변경 : target :string|string[]; 
어떤 변경 사항이 있나요?
close #32
=> :sparkles: Feat: 운동 루틴 정보 페이지 #32

src/main/reactfront/src/pages/Signup/SignupPage.styles.ts, src/main/reactfront/src/pages/Signup/SignupPage.tsx, src/main/reactfront/src/styles/Signup/SignupPage.ts
- 제목 : ➕✨ Feat: 회원가입 페이지 화면 구현 #7
회원가입 페이지 화면 구현입니다.
어떤 변경 사항이 있나요?
=> ✨ Feat: 회원가입 페이지 화면 구현 #7

src/main/reactfront/src/components/calendar/Calendar.styles.ts, src/main/reactfront/src/pages/mypage/MyHome.tsx, src/main/reactfront/src/pages/mypage/MyPageLayout.tsx
마이페이지 화면 레이아웃 수정
마이페이지 내 페이지들을 header 와 footer 너비 만큼 맞추고, sideNavBar 는 그 좌측에 위치하도록 변경
어떤 변경 사항이 있나요?
close #48
=> 💄 Design: 마이페이지 화면 레이아웃 수정 #48

src/main/reactfront/src/components/ListTable/ListTable.styles.ts, src/main/reactfront/src/components/ListTable/ListTable.tsx, src/main/reactfront/src/components/ListTable/StyledColumn.styles.ts, src/main/reactfront/src/components/ListTable/StyledColumn.tsx
ul, li를 활용한 테이블 제작
props를 통해 데이터를 전달하면 테이블이 만들어지도록 공용 컴포넌트 제작
어떤 변경 사항이 있나요?
close #36
=> ✨ Feat: 리스트형 테이블 제작

src/main/reactfront/src/components/cardList/CardList.tsx, src/main/reactfront/src/components/productCard/ProductCard.tsx, src/main/reactfront/src/pages/mall/fittness.tsx, src/main/reactfront/src/pages/mall/food.tsx, src/main/reactfront/src/pages/mall/mainProduct.tsx, src/main/reactfront/src/pages/mall/supplemnet.tsx
♻️ Refactor: CardList Propstype 및 food.tsx , ProductCard.tsx #60
CardList Propstype  target 수정 
food.tsx , ProductCard.tsx  파일 오류 수정
CardList Propstype  
더미데이터 타입을 받아 들이지 못하는 오류 발생
target : string => target : string | string[] ; 변경 하여 해결
food.tsx , ProductCard.tsx  파일 오류 수정
문법 오탈자 수정 및 파일 export import 수정
어떤 변경 사항이 있나요?
close #60
=> ♻️ Refactor: CardList Propstype 및 food.tsx , ProductCard.tsx #60

src/main/reactfront/package-lock.json, src/main/reactfront/package.json, src/main/reactfront/src/components/contentDetail/ContentDetail.styles.ts, src/main/reactfront/src/components/contentDetail/ContentDetail.tsx, src/main/reactfront/src/components/csCenter/FAQ/FAQListItem.styles.ts, src/main/reactfront/src/components/csCenter/FAQ/FAQListItem.tsx, src/main/reactfront/src/components/csCenter/FAQ/FAQLists.styles.ts, src/main/reactfront/src/components/csCenter/FAQ/FAQLists.tsx, src/main/reactfront/src/components/csCenter/checkBox/CheckBox.styles.ts, src/main/reactfront/src/components/csCenter/checkBox/CheckBox.tsx, src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryListItem.tsx, src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryLists.tsx, src/main/reactfront/src/components/csCenter/inquiry/inquiryList/inquiryListItem.styles.ts, src/main/reactfront/src/components/csCenter/inquiry/inquiryList/inquiryLists.styles.ts, src/main/reactfront/src/components/csCenter/inquiry/newInquiry/NewInquiryModal.styles.ts, src/main/reactfront/src/components/csCenter/inquiry/newInquiry/NewInquiryModal.tsx, src/main/reactfront/src/pages/csCenter/ClientService.tsx, src/main/reactfront/src/pages/csCenter/Event.tsx, src/main/reactfront/src/pages/csCenter/EventDetail.tsx, src/main/reactfront/src/pages/csCenter/FAQ.tsx, src/main/reactfront/src/pages/csCenter/Inquiry.tsx, src/main/reactfront/src/pages/csCenter/Notice.tsx, src/main/reactfront/src/pages/csCenter/NoticeDetail.tsx, src/main/reactfront/src/styles/csCenter/ClientServie.styles.ts, src/main/reactfront/src/styles/csCenter/FAQ.styles.ts, src/main/reactfront/src/styles/csCenter/Inquiry.styles.ts, src/main/reactfront/src/types/MainDummyData.ts
FitOn 사이트의 고객센터 페이지(CS Center) 제작
- 공지사항, 이벤트, FAQ, 1:1문의로 이동할 수 있도록 구현
- 1:1 문의는 모달창을 이용하여 글을 남길수 있도록 제작
- 한 페이지의 15개의 글이 보이도록 해야함 (페이징 기능 시 고려)
(아래의 페이지 이미지 사진 상에 있는 가로로 긴 선은 스크린샷 과정에서 생긴 선이므로 신경 안쓰셔도 됩니다!)
- 공지사항 페이지 (이벤트 페이지와 형식 동일)
- FAQ 페이지
- 1:1 문의 페이지 & 문의글 등록
어떤 변경 사항이 있나요?
- 문의 작성 모달창에 대한 피드백 요청
- mui icon 관련 이슈로 인해 node_modules 재설치 진행, @mui/icons-material 버전 5.15.15 -> 5.15.18 로 변경
- 에러 사항 있는지 확인 부탁
close #35
=> ✨ Feat: 고객센터 페이지 제작 #35

src/main/java/com/spring/myapp/config/WebConfig.java
클라이언트 사이드 라우팅을 위해 WebConfig 추가
현재 URL을 직접 입력하여 이동할 경우 ex) http://localhost:8080/new-feature
Spring Boot가 해당 경로를 인식하지 못해 404 오류가 발생
모든 일치하지 않는 경로를 index.html로 포워딩하도록 WebConfig 추가
이를 통해 React Router가 클라이언트 사이드 라우팅을 올바르게 처리할 수 있도록 함
- com.spring.myapp.config 패키지에 WebConfig 클래스 추가.
- WebConfig를 통해 모든 일치하지 않는 경로를 index.html로 포워딩하도록 설정.
어떤 변경 사항이 있나요?
close #64
=> ✨ Feat: 클라이언트 사이드 라우팅을 위해 WebConfig 추가 #64

package-lock.json, src/main/reactfront/package-lock.json, src/main/reactfront/package.json, src/main/reactfront/src/.eslintrc.ts, src/main/reactfront/src/.prettierrc.json, src/main/reactfront/src/App.tsx, src/main/reactfront/src/components/productDetail/BasicRating.tsx, src/main/reactfront/src/components/productDetail/ImageDetail.styled.ts, src/main/reactfront/src/components/productDetail/ImageDetail.tsx, src/main/reactfront/src/components/productDetail/ProductExplain.tsx, src/main/reactfront/src/components/productDetail/PurchasePanel.styles.ts, src/main/reactfront/src/components/productDetail/PurchasePanel.tsx, src/main/reactfront/src/components/productDetail/PurchasePanelBtn.tsx, src/main/reactfront/src/components/productDetail/QuantityInput.tsx, src/main/reactfront/src/components/productDetail/UnstyledSelectForm.tsx, src/main/reactfront/src/components/tab/ProductDescription.tsx, src/main/reactfront/src/components/tab/QuestionBoard.tsx, src/main/reactfront/src/components/tab/QuestionModal.tsx, src/main/reactfront/src/components/tab/ReviewCombine.styles.ts, src/main/reactfront/src/components/tab/ReviewCombine.tsx, src/main/reactfront/src/components/tab/Tab.tsx, src/main/reactfront/src/components/tab/moreViewBtn.tsx, src/main/reactfront/src/pages/productDetail/productDetail.tsx, src/main/reactfront/src/types/question.ts, src/main/reactfront/src/types/reviewData.ts
상품 구매 패널 및 상세 페이지, 리뷰, 상품문의를 Tab으로 구현
- 구매 수량 및 상품 옵션 선택 구현
- 상품 상세 Tab (버튼을 이용하여 상세 페이지 전체 또는 일부 보기) 구현
- 리뷰 Tab 화면 구현
- 상품 문의 작성 구현
- 상품 후기 화면 구현
어떤 변경 사항이 있나요?
추가 구현 필요
- 베스트 리뷰 (좋아요 순)
- 상품 문의 판매자 답변(대댓글)
- Related to: #38
close #38
=> ✨ Feature: 상품 상세 페이지 구현 #38

build.gradle, src/main/java/com/spring/myapp/config/S3Config.java
AWS S3 클라이언트 설정을 위한 S3Config 클래스 및 의존성 추가
- S3Config 클래스 추가
- build.gradle에 의존성 추가
어떤 변경 사항이 있나요?
close #67
=> ✨ Feat: AWS S3 클라이언트 설정을 위한 S3Config 클래스 및 의존성 추가 #67

src/main/reactfront/package-lock.json, src/main/reactfront/package.json
babel plugin 누락으로 인한 오류 수정 
@babel/plugin-proposal-private-property-in-object": "^7.21.11" 버전으로 설치
어떤 변경 사항이 있나요?
close #73
=> 🐛 Fix : BABEL BUG fix #73

build.gradle
SpringDoc OpenAPI 의존성 추가 및 Swagger UI 설정
- build.gradle 파일에 springdoc-openapi-starter-webmvc-ui:2.0.3 의존성 추가
- 자동 API 문서화를 위해 Swagger UI 활성화
어떤 변경 사항이 있나요?
close #75
=> ✨ Feat: SpringDoc OpenAPI 의존성 추가 및 Swagger UI 설정 #75

src/main/reactfront/src/components/information/CommentInputField.styles.ts, src/main/reactfront/src/components/information/CommentInputField.tsx, src/main/reactfront/src/components/information/CommentList.tsx, src/main/reactfront/src/components/information/CommentListItem.tsx, src/main/reactfront/src/components/information/StyledCommentItem.styles.ts, src/main/reactfront/src/components/information/StyledCommentItem.tsx, src/main/reactfront/src/pages/information/Info.tsx, src/main/reactfront/src/pages/information/InfoDetail.tsx, src/main/reactfront/src/styles/information/Info.styles.ts, src/main/reactfront/src/styles/information/InfoDetail.styles.ts, src/main/reactfront/src/types/MainDummyData.ts
운동 정보글 페이지 제작
운동 정보글 게시판, 디테일, 댓글창 제작
- 전체 글 게시판
- 디테일
어떤 변경 사항이 있나요?
댓글 생성 기능은 백엔드 구현시 리액트에서 바로 업데이트 후 뒷단에서 데이터 넘길 수 있도록 구현 예정
close #34
=> ✨ Feat: 정보 페이지 제작 #34

.gitignore
.gitignore 파일 업데이트
- 빌드된 정적 파일 및 로그 파일 무시
어떤 변경 사항이 있나요?
close #100
=> 🛠️ Chore: .gitignore 파일 업데이트 #100

src/main/reactfront/src/pages/signin/SigninPage.tsx, src/main/reactfront/src/pages/signup/SignupPage.tsx
✨ Feature: 이메일/비밀번호 찾기 페이직 구현 #99
이메일/비밀번호 찾기 페이지(모달창)구현입니다.
어떤 변경 사항이 있나요?
=> ✨ Feature: 이메일/비밀번호 찾기 페이직 구현 #99

.gitignore
🛠️ Chore: .gitignore 파일 업데이트 #100
.gitignore 파일 업데이트
- 빌드된 정적 파일 및 로그 파일 무시
어떤 변경 사항이 있나요?
close #103
=> 🛠️ Chore: .gitignore 파일 업데이트 #103

src/main/reactfront/src/App.tsx, src/main/reactfront/src/pages/administrator/CommunityListPage.tsx, src/main/reactfront/src/pages/administrator/EtcInquiryListPage.tsx, src/main/reactfront/src/pages/administrator/ItemInquiryListPage.tsx, src/main/reactfront/src/pages/administrator/ItemListPage.tsx, src/main/reactfront/src/pages/administrator/ItemRegisterPage.tsx, src/main/reactfront/src/pages/administrator/MemberListPage.tsx, src/main/reactfront/src/pages/administrator/PostListPage.tsx, src/main/reactfront/src/pages/administrator/ReviewListPage.tsx
관리자 페이지 라우터 경로 수정
- 상품 등록, 정보 등록 페이지 경로 수정, 각 버튼 경로 변경
post-register -> administrator/post-register , item-register -> administrator/item-register
- 관리자 페이지 내에 데이터가 없을 때 레이아웃 깨짐 현상 방지를 위해서 최소 높이 설정
어떤 변경 사항이 있나요?
close #123
=> ♻️ Refactor: 관리자페이지 라우터 경로 수정 #123

package-lock.json
package-lock.json 파일 삭제
불필요하게 업로드된 파일 package-lock.json 파일 삭제
어떤 변경 사항이 있나요?
=> 🔥 Remove: package-lock.json 파일 삭제

src/main/reactfront/src/components/cardList/CardList.tsx, src/main/reactfront/src/components/contentCard/ContentCard.tsx, src/main/reactfront/src/components/swiper/SwiperList.tsx, src/main/reactfront/src/pages/information/InfoDetail.tsx, src/main/reactfront/src/types/MainDummyData.ts
공통으로 사용하는 카드리스트 컴포넌트 수정
- 운동 정보페이지에서 nickname 을 활용, 루틴 페이지에서는 routineParts 활용
- target -> routineParts로 변경
- 추가 props 없이 이미 받은 pageURL 활용
-> if문 사용으로 임시 처방!
어떤 변경 사항이 있나요?
#129
=> ♻️ Refactor: 카드리스트 컴포넌트 수정

src/main/reactfront/src/components/productCard/ProductCard.styles.ts, src/main/reactfront/src/components/productCard/ProductCard.tsx, src/main/reactfront/src/pages/mall/Mall.tsx, src/main/reactfront/src/pages/mall/ProductCardList.tsx
디자인 수정
:recycle: Mall.tsx
뭉개지던 디자인 수정
ProductCard.styles.ts
-상품 명  아래의 특성을 적용하여 일관된 카드 디자인 유지
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis; 
ProductCard.tsx
-Grid2 로 변경하여 적용
어떤 변경 사항이 있나요?
close #149
=> :recycle: Mall.tsx #149

src/main/reactfront/src/components/productCard/ProductCard.styles.ts, src/main/reactfront/src/components/productCard/ProductCard.tsx, src/main/reactfront/src/pages/mall/Mall.tsx, src/main/reactfront/src/pages/mall/ProductCardList.tsx
- 제목 : ➕ 유형: title #이슈번호
ex) ✨ Feat: 게시판 Create 구현 #1 (확인 후 지워주세요)
Mall.tsx 페이지에서 상품 간격이 일정하지 않은 이슈 발생
ProductCard.tsx ProductCardList.tsx ProductCard.styles.ts 수정 및
상품 가격 가시성 확보
어떤 변경 사항이 있나요?
close #151
=> ♻️ Refactor : 상품 페이지 카드 디자인 수정

src/main/java/com/spring/myapp/security/JwtTokenProvider.java
JWT 클레임 키를 camelCase로 업데이트
기존 구현에서는 JWT 클레임 키를 snake_case로 사용하고 있었습니다.
Java와 React 코드 스타일이 camelCase를 사용하므로,
JSON 형식의 JWT 클레임 키를 camelCase로 업데이트하여 전체 코드베이스에서 일관성을 유지하고자 합니다.
어떤 변경 사항이 있나요?
close #183
=> ♻️ Refactor: JWT 클레임 키를 camelCase로 업데이트

src/main/java/com/spring/myapp/order/model/Order.java, src/main/java/com/spring/myapp/order/repository/OrderMapper.java, src/main/java/com/spring/myapp/order/service/OrderService.java, src/main/java/com/spring/myapp/product/controller/ProductController.java, src/main/java/com/spring/myapp/shipping/controller/ShippingAddressController.java, src/main/java/com/spring/myapp/shipping/model/ShippingAddress.java, src/main/java/com/spring/myapp/shipping/repository/ShippingAddressMapper.java, src/main/java/com/spring/myapp/shipping/service/ShippingAddressService.java, src/main/reactfront/src/pages/order/OrderPage.tsx, src/main/reactfront/src/types/DataInterface.tsx, src/main/resources/mapper/shippingAddress/ShippingAddress.xml
✨ Feature: 상품 배송 #197 
OrderPage.tsx API 호출 및 CSS 변경
ShippingAddress 관련 파일 작성
**OrderPage.tsx**
- 기본 배송지 및 목록 불러오기
**ShippingAddress**
- Controller Model Service Repository 세팅
**Order**
- Controller Model Service Repository 세팅
어떤 변경 사항이 있나요?
close #197
=> ✨ Feature: 상품 배송지

src/main/java/com/spring/myapp/mypage/controller/UserInfoController.java, src/main/java/com/spring/myapp/mypage/dto/DeactivateAccountDTO.java, src/main/java/com/spring/myapp/mypage/dto/PasswordUpdateDTO.java, src/main/java/com/spring/myapp/mypage/dto/UserInfoAdditionalUpdateDTO.java, src/main/java/com/spring/myapp/mypage/dto/UserInfoUpdateDTO.java, src/main/java/com/spring/myapp/mypage/model/MyHomeStatistics.java, src/main/java/com/spring/myapp/mypage/model/UserInfo.java, src/main/java/com/spring/myapp/mypage/repository/UserInfoRepository.java, src/main/java/com/spring/myapp/mypage/service/UserInfoService.java, src/main/java/com/spring/myapp/security/JwtAuthenticationFilter.java, src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx, src/main/reactfront/src/components/layout/sideNavBar/StyledPersonIcon.tsx, src/main/reactfront/src/context/AuthContext.tsx, src/main/reactfront/src/pages/mypage/MyHome.tsx, src/main/reactfront/src/pages/mypage/UserInfoLoginPage.tsx, src/main/reactfront/src/pages/mypage/UserInfoPage.tsx, src/main/reactfront/src/styles/mypage/UserInfoPage.styles.ts, src/main/resources/mapper/mypage/UserInfoMapper.xml
마이페이지 회원정보 기능 구현
1. 회원정보 조회 기능 구현
- 사용자 정보를 조회하여 프론트엔드에 표시하는 기능 추가
2. 회원정보 수정 기능 구현
- 사용자 기본 정보 및 추가 정보를 수정할 수 있는 기능 추가
- 닉네임 중복 확인 버튼과 유효성 검사 로직 추가
- 휴대전화 번호의 유효성을 검사하고 사용자에게 피드백 제공
- 수정된 정보를 API로 전송하여 서버에 저장
3. 비밀번호 변경 기능 구현
- 비밀번호 변경을 위한 입력 필드와 검증 로직 추가
- 새로운 비밀번호를 입력하고 확인하여 서버에 업데이트 요청
- 비밀번호 유효성 검사 및 일치 여부 확인 기능 추가
4. 회원 탈퇴 기능 구현
- 비밀번호 확인 후 회원 탈퇴를 처리하는 기능 추가
- 회원 탈퇴 요청 시 확인 다이얼로그 표시
- 탈퇴 처리 후 로그아웃 및 리다이렉션
어떤 변경 사항이 있나요?
close #192
=> ✨ Feat: 마이페이지 회원정보 기능 구현

src/main/java/com/spring/myapp/mypage/controller/UserInfoController.java, src/main/java/com/spring/myapp/mypage/model/UserInfo.java, src/main/java/com/spring/myapp/mypage/repository/UserInfoRepository.java, src/main/java/com/spring/myapp/mypage/service/UserInfoService.java, src/main/reactfront/src/components/common/profileImage/ProfileImage.tsx, src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx, src/main/reactfront/src/components/layout/sideNavBar/StyledProfileImage.tsx, src/main/reactfront/src/pages/mypage/MyHome.tsx, src/main/reactfront/src/pages/mypage/UserInfoPage.tsx, src/main/resources/mapper/mypage/UserInfoMapper.xml
마이페이지 회원정보 회원 프로필 이미지 업로드 기능 구현
- 회원정보 페이지에서 프로필 이미지를 업로드하고 업데이트할 수 있는 기능 추가
- 프로필 이미지 업로드 및 삭제를 위한 백엔드 API 엔드포인트 작성
- 프로필 이미지 변경 및 삭제 기능 구현
- 프로필 이미지 컴포넌트 `ProfileImage` 추가
- 사용자 프로필 이미지를 표시하는 컴포넌트
- 기본 프로필 이미지와 업로드된 이미지를 렌더링하는 기능
- 프로필 이미지 업로드 모달 UI 개선
- "파일 첨부" 및 "이미지 삭제" 버튼 추가
어떤 변경 사항이 있나요?
close #205
=> ✨ Feat: 마이페이지 회원정보 회원 프로필 이미지 업로드 기능 구현

src/main/java/com/spring/myapp/community/controller/CommunityBoardCommentController.java, src/main/java/com/spring/myapp/community/controller/CommunityBoardController.java, src/main/java/com/spring/myapp/community/dto/CommunityBoardCommentDTO.java, src/main/java/com/spring/myapp/community/model/CommunityBoardUserDetails.java, src/main/java/com/spring/myapp/community/service/CommunityBoardCommentService.java, src/main/java/com/spring/myapp/community/service/CommunityBoardService.java, src/main/reactfront/src/App.tsx, src/main/reactfront/src/components/common/SelectBox.tsx, src/main/reactfront/src/components/common/button/ButtonCategoryTag.tsx, src/main/reactfront/src/components/community/Board.tsx, src/main/reactfront/src/pages/community/CommunityMain.tsx, src/main/reactfront/src/pages/community/CommunityPostEdit.tsx, src/main/reactfront/src/pages/community/NewPost.tsx, src/main/reactfront/src/pages/community/ViewPostDetail.tsx
커뮤니티 글/댓글 삭제 메서드 변경 및 댓글 route 경로 변경
커뮤니티 게시판 카테고리 버튼 필터 기능 구현
공통 컴포넌트 변경에 따른 댓글 route 수정
삭제 메서드 변경(DELETE -> PUT)
로그 삭제 및 주석 삭제
어떤 변경 사항이 있나요?
close #210
=> Refactor : 댓글 route 수정 및 커뮤니티 게시판 카테고리 버튼 필터 수정 #210

src/main/java/com/spring/myapp/mypage/controller/PostManagementController.java, src/main/java/com/spring/myapp/mypage/dto/PostManagementDto.java, src/main/java/com/spring/myapp/mypage/repository/PostManagementRepository.java, src/main/java/com/spring/myapp/mypage/service/PostManagementService.java, src/main/reactfront/src/components/genericTable/GenericTable.tsx, src/main/reactfront/src/pages/mypage/PostManagementPage.tsx, src/main/resources/mapper/mypage/PostManagementMapper.xml
마이페이지 게시글 관리 기능 구현
- 마이페이지 게시글 관리 기능 구현
- 나의 게시글 목록 조회 및 검색 기능, 페이징 구현
- 나의 게시글 수정 및 삭제 기능 구현
- 게시글 누르면 해당 상세 페이지로 이동 가능하도록 구현
- GenericTable 프론트엔드 페이징 기능 제거
루틴 게시판의 수정 및 삭제 기능은 이슈가 있어 추후 구현 예정
어떤 변경 사항이 있나요?
close #209
=> ✨ Feat: 마이페이지 게시글 관리 기능 구현

src/main/java/com/spring/myapp/cart/controller/CartController.java, src/main/reactfront/src/App.tsx, src/main/reactfront/src/components/common/Editor.tsx, src/main/reactfront/src/components/productCard/ProductCard.styles.ts, src/main/reactfront/src/pages/administrator/AdminPage.tsx, src/main/reactfront/src/pages/administrator/OrderManagementPage.tsx, src/main/reactfront/src/pages/mall/Fittness.tsx, src/main/reactfront/src/pages/mall/Food.tsx, src/main/reactfront/src/pages/mall/MallMain.tsx, src/main/reactfront/src/pages/mall/ProductCardList.tsx, src/main/reactfront/src/pages/mall/Supplement.tsx, src/main/reactfront/src/pages/shoppingBasket/ShoppingBasketPage.tsx
♻️ Refactor 쇼핑몰 카드 배치 수정 #215 
쇼핑몰 카드 배치 수정 
주문 관리 페이지 기본 틀 작성 
장바구니 상품 수량 조절
**Editor.tsx**
- 불필요 코드 제거
**CartController.java** 
- 장바구니 상품 수량 조절 기능 수정
**ShoppingBasketPage.tsx** 
- 장바구니 상품 수량 조절 버튼 추가
**AdminPage.tsx**
- SideBar 주문 관리 메뉴 추가
**App.tsx**
- OrderManagementPage.tsx 경로 추가
**OrderManagementPage.tsx**
- 주문 관리 페이지 기초 UI 작성
**Mall.tsx 하위 라우터 페이지**
**ProductCardList.tsx**
**ProductCard.styles.ts**
- 상품 간격 헤더에 맞추기
어떤 변경 사항이 있나요?
close #215
=> ♻️ Refactor : Mall 디자인 및 기타 수정 사항

src/main/reactfront/src/components/main/info/MainInfo.tsx, src/main/reactfront/src/components/main/routine/MainRoutines.tsx, src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx, src/main/reactfront/src/pages/information/InfoDetail.tsx
정보 게시판 글 관련 경로 수정
- 정보 페이지 글 삭제 & 등록 후 게시판 목록으로 이동 경로 수정
- 메인 페이지 데이터 로딩 관련 피드백 문구 수정
어떤 변경 사항이 있나요?
close #222
=> 🐛 Fix : 정보페이지 경로 관련 버그 수정 #222

src/main/java/com/spring/myapp/mypage/service/UserInfoService.java, src/main/reactfront/src/components/common/comment/StyledCommentItem.tsx, src/main/reactfront/src/components/common/profileImage/ProfileImage.tsx, src/main/reactfront/src/pages/information/Info.tsx, src/main/reactfront/src/pages/information/InfoDetail.tsx
프로필 이미지 처리 기능 수정
- ProfileImage 컴포넌트를 수정하여 userId를 선택적으로 받을 수 있도록 개선
- 프로필 이미지가 없는 경우 기본 이미지를 표시
- 프로필 이미지 업로드 시 발생하는 예외 처리 추가
어떤 변경 사항이 있나요?
close #224
=> 🐛 Fix: 프로필 이미지 처리 기능 수정

src/main/java/com/spring/myapp/mypage/controller/CommentManagementController.java, src/main/java/com/spring/myapp/mypage/dto/CommentManagementDto.java, src/main/java/com/spring/myapp/mypage/repository/CommentManagementRepository.java, src/main/java/com/spring/myapp/mypage/service/CommentManagementService.java, src/main/reactfront/src/pages/mypage/CommentManagementPage.tsx, src/main/reactfront/src/pages/mypage/PostManagementPage.tsx, src/main/resources/mapper/mypage/CommentManagementMapper.xml
마이페이지 댓글 관리 기능 구현
- 마이페이지에서 사용자가 작성한 댓글을 조회, 검색, 삭제할 수 있는 기능 구현.
- 커뮤니티 게시판, 루틴 게시판, 정보 게시판의 댓글 관리 기능 추가.
- 탭을 통해 게시판 종류별로 댓글을 필터링할 수 있도록 구현.
- 댓글 목록 UI 및 UX 개선.
- 댓글 목록에 답글 표시를 위한 아이콘 추가.
- 페이지네이션 적용.
어떤 변경 사항이 있나요?
close #227
=> ✨ Feat: 마이페이지 댓글 관리 기능 구현

src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java, src/main/java/com/spring/myapp/informationBoard/repository/InfoMapper.java, src/main/java/com/spring/myapp/informationBoard/service/InfoService.java, src/main/reactfront/src/pages/mall/Mall.tsx, src/main/reactfront/src/pages/mall/MallMain.tsx, src/main/resources/mapper/informationBoard/InfoMapper.xml
정보 게시판 글 삭제시 관련 댓글 삭제
정보 게시판에서 특정 글을 삭제할 경우, 등록되어 있던 댓글&대댓글 삭제처리
어떤 변경 사항이 있나요?
close #225
=> ✨ Feat: 정보 게시판 글 삭제시 관련 댓글 삭제 #225

README.md
READ ME upadate
- Read Me 각 페이지 스크린샷 이미지 및 설명 추가
어떤 변경 사항이 있나요?
close #230
=> 📃Docs : Update README.md #230

src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
정보글 등록 경로 에러 해결
운동 정보글 등록 시 axios 경로 에러 해결
어떤 변경 사항이 있나요?
close #231
=> 🐛 Fix : 정보글 등록 경로 에러 해결 #231

.github/workflows/cicd.yml, Dockerfile, build.gradle, src/main/java/com/spring/myapp/common/controller/HealthCheckController.java, src/main/java/com/spring/myapp/common/controller/WebController.java, src/main/java/com/spring/myapp/config/SecurityConfig.java, src/main/java/com/spring/myapp/config/WebConfig.java, src/main/java/com/spring/myapp/user/controller/NaverAuthController.java, src/main/reactfront/.eslintrc.ts, src/main/reactfront/package.json, src/main/reactfront/public/index.html, src/main/reactfront/src/context/AuthContext.tsx, src/main/reactfront/src/pages/mypage/MyHome.tsx, src/main/resources/application.yml
배포 및 CI/CD 환경 설정 완료
AWS EC2, Docker, Nginx, GitHub Actions 기반의 CI/CD 파이프라인을 설정하고, 배포 환경을 최적화하는 작업을 진행하였습니다. 또한, Route 53 및 Amazon Certificate Manager를 사용하여 HTTPS를 지원하는 도메인 설정을 완료하였습니다.
- CI/CD 파이프라인 구성
- `main` 브랜치에 대한 푸시 발생 시 GitHub Actions를 통해 CI/CD가 자동으로 실행되도록 설정.
- 환경 변수를 설정하고 React 프론트엔드와 Spring Boot 백엔드의 빌드를 진행.
- Docker 이미지를 빌드하고 DockerHub에 최신 이미지를 푸시하는 단계를 추가하여 최신 상태를 유지.
- 배포 단계에서 현재 서버의 상태를 확인하고, 새로운 버전을 무중단 배포하는 방식으로 Nginx Upstream을 전환하도록 구성.
- Docker & Nginx
- `Dockerfile`을 작성하여 애플리케이션의 배포 환경을 Docker 기반으로 설정.
- AWS EC2에서 Docker와 Nginx를 사용하여 Blue/Green 배포 전략을 활용한 무중단 배포 구현.
- 서버의 현재 상태를 확인하고, 업스트림을 적절히 설정하여 배포 진행.
- Nginx를 통해 업스트림을 동적으로 변경하고, 배포 후 사용하지 않는 서버를 정리.
- `default.conf`에 403, 404 오류 발생 시 프론트엔드 SPA 라우팅 문제를 해결하기 위한 설정 추가.
- 애플리케이션 설정
- Spring Boot의 `application.yml` 파일을 …
=> 🛠️ Chore: 배포 및 CI/CD 환경 설정 완료
